{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name | quote }}
  namespace: argocd
spec:
  project: {{ .project | default "default" | quote }}
  source:
    repoURL: {{ .source.repoURL | quote }}
    path: {{ .source.path | quote }}
    targetRevision: {{ .source.targetRevision | default "main" | quote }}
    helm:
      valueFiles:
{{- range .source.helm.valueFiles }}
        - {{ . | quote }}
{{- end }}
  destination:
    server: {{ .destination.server | quote }}
    namespace: {{ .destination.namespace | quote }}
  syncPolicy:
    automated:
      prune: {{ .syncPolicy.automated.prune | default true }}
      selfHeal: {{ .syncPolicy.automated.selfHeal | default true }}
---
{{- end }}
